// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"

import ApplicationController from "./application_controller"
import TurboFrameController from './turbo-frame_controller'
import OrderController from './order_controller'

application.register('application', ApplicationController)
application.register('frame', TurboFrameController)
application.register('order', OrderController)
